# Generated by Django 3.2.25 on 2024-04-21 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0010_auto_20240407_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
