# Generated by Django 3.0.5 on 2024-07-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0013_auto_20240710_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecustomer',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
